var i1="select-resolution",i2="toggle-polygon",c1={value:"geohash",text:"Geohash",geoService:Geohash,resolutionOptions:{name:"Geohash precision",min:0,max:15,selected:6}},c2={value:"geohex",text:"GeoHex",geoService:GEOHEX,resolutionOptions:{name:"GeoHex level",min:0,max:15,selected:6}},c3={value:"h3",text:"H3",geoService:h3,resolutionOptions:{name:"H3 resolution",min:0,max:15,selected:7}},cs=[c1,c2,c3],
zs=[],m1=void 0,sS=cs[2];document.addEventListener("DOMContentLoaded",im1);
function im1(){void 0!=m1&&(m1.off(),m1.isFullscreen()&&m1.toggleFullscreen(),m1.remove());var a=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",{id:"mapbox.comic",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),c=
L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",{id:"mapbox.dark",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),f=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",
{id:"mapbox.emerald",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),d=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",{id:"mapbox.high-contrast",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),
e=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",{id:"mapbox.light",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),h=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",
{id:"mapbox.outdoors",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),k=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",{id:"mapbox.pencil",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),
l=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",{id:"mapbox.pirates",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),m=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",
{id:"mapbox.run-bike-hike",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),n=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",{id:"mapbox.satellite",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),
g=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",{id:"mapbox.streets",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),p=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",
{id:"mapbox.streets-basic",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),q=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",{id:"mapbox.streets-satellite",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'}),
r=L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw",{id:"mapbox.wheatpaste",attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery \u00a9 <a href="https://www.mapbox.com/">Mapbox</a>'});m1=L.map("mapid",{center:[51.505,-.09],layers:[g],zoom:13,fullscreenControl:{pseudoFullscreen:!1}});
m1.on("locationfound",dp1);m1.on("locationerror",locationError);m1.on("moveend",dp1);L.control.measure({position:"topleft",activeColor:"blue",completedColor:"blue"}).addTo(m1);SS=L.Control.extend({onAdd:function(b){b=L.DomUtil.create("div","leaflet-bar");b.classList.add("custom-control");var a=document.createTextNode("Encoding: ");b.appendChild(a);var c=L.DomUtil.create("select","",b);as1(c,cs,sS.value);c.addEventListener("change",
function(b){sS=cs[c.selectedIndex];im1()});return b},onRemove:function(b){}});sS0=function(b){return new SS(b)};sS0({position:"topright"}).addTo(m1);SR=L.Control.extend({onAdd:function(b){b=L.DomUtil.create("div","leaflet-bar");b.classList.add("custom-control");var a=document.createTextNode(sS.resolutionOptions.name+": ");b.appendChild(a);a=L.DomUtil.create("select","",b);a.id=i1;for(var c=
[],d=sS.resolutionOptions.min;d<=sS.resolutionOptions.max;d++)c.push({text:d,value:d});as1(a,c,sS.resolutionOptions.selected);a.addEventListener("change",dp1);return b},onRemove:function(b){}});sR0=function(b){return new SR(b)};sR0({position:"topright"}).addTo(m1);L.esri.Geocoding.geosearch({position:"topright",zoomToResult:!1,useMapBounds:!1,allowMultipleResults:!1}).addTo(m1).on("results",
function(b){void 0!==b.latlng&&m1.flyTo(b.latlng)});CP=L.Control.extend({onAdd:function(b){b=L.DomUtil.create("div","leaflet-control");b.classList.add("leaflet-bar");var a=L.DomUtil.create("a","leaflet-bar-part",b);a.href="";a.title="Show Your Location";a.addEventListener("click",ul1);a=L.DomUtil.create("i","fas",a);a.classList.add("fa-crosshairs");a.classList.add("fa-lg");return b},onRemove:function(a){}});cp0=function(a){return new CP(a)};
cp0({position:"topright"}).addTo(m1);TP=L.Control.extend({onAdd:function(a){a=L.DomUtil.create("label","polygon-switch");a.title="Turn polygon on/off";var b=L.DomUtil.create("input","",a);b.type="checkbox";b.id=i2;b.checked=!0;b.addEventListener("click",dp1);L.DomUtil.create("span","polygon-slider round",a);return a},onRemove:function(a){}});tp0=function(a){return new TP(a)};tp0({position:"topright"}).addTo(m1);L.control.layers({Comic:a,
Emerald:f,Dark:c,"High contrast":d,Light:e,Outdoors:h,Pencil:k,Pirates:l,"Run, bike, hike":m,Satellite:n,Streets:g,"Streets basic":p,"Streets satellite":q,"Wheat paste":r}).addTo(m1);ul1()}function as1(a,c,f){for(var d=0;d<c.length;d++){var e=document.createElement("option");e.text=c[d].text;e.value=c[d].value;e.selected=c[d].value==f;a.add(e)}}
function dp1(){for(i=0;i<zs.length;i++)zs[i].rm1();zs=[];if(document.getElementById(i2).checked){var a=document.getElementById(i1),c=m1.getBounds();a=parseInt(a.options[a.selectedIndex].value);zs=sS.geoService.gpf0(c.getSouth(),c.getNorth(),c.getWest(),c.getEast(),a);for(i=0;i<zs.length;i++)zs[i].dm1(m1)}}
function ul1(){navigator.geolocation.getCurrentPosition(function(a){m1.flyTo([a.coords.latitude,a.coords.longitude])},locationError)}function locationError(a){a=L.popup();a.setLatLng(m1.getCenter()).setContent("Error: The Geolocation service failed.");a.openOn(m1);dp1()}
G1.prototype.dm1=function(a){a=L.polygon(this.coords,{weight:1,fillOpacity:.1}).addTo(a);a.bindTooltip(this.string,{sticky:!0});a.on("mouseover",function(a){this.setStyle({color:"red",fillOpacity:0,weight:3})});a.on("mouseout",function(a){this.setStyle({color:"#3388ff",fillOpacity:.1,weight:1})});this.polygon=a};G1.prototype.rm1=function(){this.polygon.remove()};